### PR TITLE
Add support for prettyprinting C-API named tuples

### PR DESCRIPTION
**Pull request by tommikaikkonen**
Fixes https://github.com/tommikaikkonen/prettyprinter/issues/37 by adding basic support for [C-API named tuples](https://docs.python.org/3/c-api/tuple.html#c.PyStructSequence_NewType)

Uses a slightly hacky (but valid) way of resolving namedtuple elements to their fieldnames that relies on the namedtuple constructor allowing for arbitrary tuple elements. This lack of validation seems to be the case for `posix.uname_result` and `time.struct_time` constructors, at least.

As with other prettyprinters in this package, I have made the output evaluable. For the current `__repr__` implementation of the c-namedtuple, [this is not the case](https://bugs.python.org/issue5907). C-namedtuples don't allow passing arguments as keyword arguments, so we must pass in a tuple and communicate the fieldnames via comments. This is what the output for `time.strptime("2000", "%Y")` looks like:

```python
time.struct_time((
    2000,  # tm_year
    1,  # tm_mon
    1,  # tm_mday
    0,  # tm_hour
    0,  # tm_min
    0,  # tm_sec
    5,  # tm_wday
    1,  # tm_yday
    -1  # tm_isdst
))
```

@anntzer what are your thoughts? I think the version with keyword arguments looks nicer, but I know that I among other people appreciate being able to copy & paste output from prettyprinter (or any other shell output) and paste it into code and have it just work.

### CODE REVIEW

**Comment by anntzer** [comment]
FWIW, here's the list of all cross-platform c-namedtuples I found by grepping the cpython codebase:
```
import os, resource, sys, time

for obj in [
        os.stat(os.__file__),
        os.times(),
        os.get_terminal_size(),
        resource.getrusage(resource.RUSAGE_SELF),
        sys.flags,
        sys.float_info,
        sys.get_asyncgen_hooks(),
        sys.hash_info,
        sys.thread_info,
        sys.version_info,
        time.localtime(),
]:
    print(type(obj))
```
(there are a few more that are unix-only or windows-only, e.g. os.uname() and sys.getwindowsversion()).

I haven't tested whether this PR handles all of them fine, you may want to give them a try?

---

Passing individual object()s is nicer than parsing the repr() for sure...

I like the version with keyword arguments more, but I definitely see your point about eval()uatability so I'll defer to your judgment here.

**Comment by tommikaikkonen** [comment]
Thanks for supplying that list @anntzer. After adding a test case with all of those values, the passing `object()`s approach didn't work so well. Many of them don't allow constructing our own instances that we needed to resolve the field names.

I implemented an approach that parses the repr for the field names like you initially suggested. It's quite a bit simpler, so I ended up applying that to all of the values, even if the `object()` approach would have worked. The resolved field names are memoized so we pay the parsing price only when we first print a value of a namedtuple type.

**Comment by anntzer** [comment]
Ah, using ast for parsing is cute :)
Thanks, this looks great to me.

**Comment by tommikaikkonen** [comment]
Released in `0.16.0`.

**Pull request merged**
